### ISSUE TITLE
GitHub tags missing

### ISSUE THREAD

**Issue by jayvdb** [ambitioninc/pip-conflict-checker#15]
PyPI has 0.6.0 , and there is no tag here for that.

Also the sdist doesnt include tests, so I have no way to get versioned tests in order to finish https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pip-conflict-checker

**Comment by jayvdb** [comment]
ping @jaredlewis

**Comment by jaredlewis** [comment]
this project is not maintained anymore as this is now built into pip with `pip check`
