### ISSUE TITLE
pip check

### ISSUE THREAD

**Issue by wesleykendall** [ambitioninc/pip-conflict-checker#7]
@jaredlewis I just discovered that pip 9.0 introduces "pip check". I tried using ambition conflict checker for something that was an obvious conflict in a requirements file, but it didn't catch it. `pip check` found it though and prints a pretty error message. Just wanted to put this here so it's known

**Comment by wesleykendall** [comment]
I can also try to make a requirements file that reproduces the error if you want to try to debug. The requirements file I'm using has proprietary stuff in it and I can't paste it at the moment

**Comment by jaredlewis** [comment]
Wow its about time, only took them NINE versions. Thanks for letting me know, that is awesome, can probably just mark this as deprecated now

**Comment by wesleykendall** [comment]
Haha for real! I'll close this issue. Just wanted to let ya know
